### PR TITLE
Change path structure to move date

### PR DESCRIPTION
**Pull request by lesserwhirls**
See Unidata/TdsConfig#27

### CODE REVIEW

**Comment by dopplershift** [comment]
Why not modify the pqact to explicitly pass in the directory structure to `goes-restitch.py`? Then this won't be dependent on other updates.

**Comment by lesserwhirls** [comment]
I do in the [TdsConfig PR](https://github.com/Unidata/TdsConfig/pull/28/files#diff-1228768928538e0111a51d3d174c0662), but I also change the default here so that anyone else who happens to use this will get a directory structure that plays nice with NcML aggs by default.

**Comment by dopplershift** [comment]
Ok, I was just confused because the PR you linked to says it depends on this one.

**Comment by lesserwhirls** [comment]
Yep, that comment was a derp on my part.

**Pull request merged**
